#!/usr/bin/python3
import sys, argparse, uuid, libvirt, lxml.etree

# parse arguments
parser = argparse.ArgumentParser(prog='virtdeclare',description='Control libvirt domains declaratively and idempotently.')
parser.add_argument('--connect', action='store', required=True, metavar='URI', help='connection URI (e.g. qemu:///session)')
specgroup = parser.add_mutually_exclusive_group(required=True)
specgroup.add_argument('--define', action='store', metavar='PATH', help='XML domain definition file path')
specgroup.add_argument('--name', action='store', metavar='ID', help='domain name or UUID')
parser.add_argument('--state', action='store', choices = ['running','stopped'], required=True, help='state to put domain in')
parser.add_argument('--auto', action='store_true', help='set autostart to match state')
parser.add_argument('-v', '--verbose', action='store_true', help='report actions to stderr')
args = parser.parse_args()

# Switch off annoying libvirt stderr messages
# https://stackoverflow.com/a/45543887
def libvirt_callback(userdata, err):
    pass
libvirt.registerErrorHandler(f=libvirt_callback, ctx=None)

conn = libvirt.open(args.connect)

def log(domid,msg):
    if args.verbose:
        print ("domain " + str(uuid.UUID(bytes=domid)) + ": " + msg, file=sys.stderr)

# fetch / define domain
if args.define:
    domxml = lxml.etree.parse(args.define)
    domxmlstr = lxml.etree.canonicalize(domxml,strip_text=True)
    domid = uuid.UUID(domxml.find("uuid").text).bytes
    try:
        olddomain = conn.lookupByUUID(domid)
    except libvirt.libvirtError:
        olddomain = None
    if olddomain:
        olddomxml = lxml.etree.fromstring(olddomain.XMLDesc())
        olddomxmlstr = lxml.etree.canonicalize(olddomxml,strip_text=True)
        if olddomxmlstr == domxmlstr:
            domain = olddomain
        else:
            if olddomain.isActive():
                log (domid,"destroy")
                olddomain.destroy()
            log (domid,"undefine")
            olddomain.undefine()
            log (domid,"define")
            domain = conn.defineXML(domxmlstr)
    else:
        log (domid,"define")
        domain = conn.defineXML(domxmlstr)
else:
    try:
        domid = uuid.UUID(args.name).bytes
        domain = conn.lookupByUUID(domid)
    except ValueError:
        domain = conn.lookupByName(args.name)

# set state
match args.state:
    case "running":
        if not domain.isActive():
            log (domain.UUID(),"create")
            domain.create()
    case "stopped":
        if domain.isActive():
            log (domain.UUID(),"destroy")
            domain.destroy()

# set autostart
if args.auto:
    match args.state:
        case "running":
            log (domain.UUID(),"setAutostart True")
            domain.setAutostart(True)
        case "stopped":
            log (domain.UUID(),"setAutostart False")
            domain.setAutostart(False)
