#!/usr/bin/python3
import sys, argparse, uuid, lxml.etree, libvirt, nixvirt

# parse arguments
parser = argparse.ArgumentParser(prog='virtdeclare',description='Define and control libvirt objects idempotently.')
parser.add_argument('-v', '--verbose', action='store_true', help='report actions to stderr')
parser.add_argument('--connect', action='store', required=True, metavar='URI', help='connection URI (e.g. qemu:///session)')
parser.add_argument('--type', action='store', required=True, choices = nixvirt.objectTypes, help='object type')
specgroup = parser.add_mutually_exclusive_group(required=True)
specgroup.add_argument('--define', action='store', metavar='PATH', help='XML object definition file path')
specgroup.add_argument('--uuid', action='store', metavar='ID', help='object UUID')
specgroup.add_argument('--name', action='store', metavar='ID', help='object name')
parser.add_argument('--state', action='store', choices = ['active','inactive'], help='state to put object in')
parser.add_argument('--auto', action='store_true', help='set autostart to match state')

args = parser.parse_args()

setstate = args.state

try:
    oc = nixvirt.getObjectConnection(args.connect,args.type,args.verbose)

    # fetch / define object
    if args.define:
        with open(args.define,"r") as f:
            specDef = f.read()
        specDefXML = lxml.etree.fromstring(specDef)
        specUUID = uuid.UUID(specDefXML.find("uuid").text).bytes
        found = oc.fromUUIDOrNone(specUUID)
        if found:
            foundActive = found.isActive()
            foundDef = found.XMLDesc()
            foundDefXML = lxml.etree.fromstring(foundDef)
            foundName = foundDefXML.find("name").text
            specName = specDefXML.find("name").text
            if foundName != specName:
                found.undefine()
            oc.vreport(specUUID,"redefine")
            subject = oc.fromXML(specDef)
            subjectDef = subject.XMLDesc()
            defchanged = foundDef != subjectDef
            oc.vreport(specUUID,"changed" if defchanged else "unchanged")
            if defchanged and (setstate != "inactive"):
                found.deactivate()
                if foundActive:
                    setstate = "active"
        else:
            oc.vreport(specUUID,"define new")
            subject = oc.fromXML(specDef)
    elif args.uuid:
        specUUID = uuid.UUID(args.uuid).bytes
        subject = oc.fromUUID(specUUID)
    else:
        subject = oc.fromName(args.name)

    # set state
    match setstate:
        case "active":
            subject.activate()
        case "inactive":
            subject.deactivate()

    # set autostart
    if args.auto:
        match args.state:
            case "active":
                subject.setAutostart(True)
            case "inactive":
                subject.setAutostart(False)

except libvirt.libvirtError as err:
    print ("virtdeclare: error:", err, file=sys.stderr)
    sys.exit(1)
