#!/usr/bin/python3
import sys, argparse, uuid, libvirt, lxml.etree, os, nixvirt

# parse arguments
parser = argparse.ArgumentParser(prog='virtpurge',description='Delete unwanted libvirt objects idempotently.')
parser.add_argument('-v', '--verbose', action='store_true', help='report actions to stderr')
parser.add_argument('--connect', action='store', required=True, metavar='URI', help='connection URI (e.g. qemu:///session)')
parser.add_argument('--type', action='store', required=True, choices = ['domain','network'], help='object type')
parser.add_argument('--keep', action='store', required=True, metavar='PATH', help='path to list of files to keep')

args = parser.parse_args()

oc = nixvirt.getObjectConnection(args.connect,args.type,args.verbose)

lvobjs = oc.getAllLV()

uuids = map (lambda lvobj: lvobj.UUID(), lvobjs)

with open(args.keep,"r") as f:
    keepText = f.read()

for uuid in uuids:
    print("keep: ",uuid, file=sys.stderr)

sys.exit(3)
